version: '3.7'

services:
  grpc-service:
    container_name: container-grpc
    image: grpc-service
    build:
      context: .
      dockerfile: grpcServer/vscode.dockerfile
      target: debug
    environment:
      CONN_STRING: "Falta definir"
    volumes:
      - ../src:/src
      - ../../:/root/debug    
    ports:
      - 8008:5000
    networks:
      - debugando-no-container 

volumes:
  dbvolume:

networks:
  debugando-no-container:
