version: '3.7'

services:
  webapi-service:
    container_name: container-webapi
    image: webapi-service
    build:
      context: .
      dockerfile: vscode.dockerfile
      #target: debug
    environment:
      CONN_STRING: "Falta definir"
    volumes:
      - ../src:/src
      - ../../:/root/debug    
    ports:
      - 8007:5000
    networks:
      - debugando-no-container 

volumes:
  dbvolume:

networks:
  debugando-no-container:
